services:

  scheduler:
    build: .
    env_file: .env
    networks:
      - pulsorch_worker
    command: python -m worker.scheduler


  triggerier:
    build: .
    env_file: .env
    networks:
      - pulsorch_worker
    command: python -m worker.triggerier

networks:
  pulsorch_worker: 
    external: true
