[project]
name = "worker"
version = "0.1.0"

dependencies = [
    "httpx",
    "pydantic",
    "python-dotenv"
]

[project.optional-dependencies]
dev = [
    "mypy",
    "ruff",
    "flake8",
    "pytest"
]